name: pcaweb
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  http: ^0.13.5
  flutter_svg: ^1.1.6
  url_launcher: ^6.3.1
  flutter_screenutil: ^5.8.0
  image_picker_for_web: ^3.0.6
  audioplayers: ^6.1.0
  path_provider: ^2.0.11
  path: ^1.8.3
  fl_chart: ^0.55.2
  list_wheel_scroll_view_nls: ^0.0.3
  go_router: ^14.6.2
  percent_indicator: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/pitball_logo_circular_hd.png"

flutter:
  uses-material-design: true

  assets:
    - assets/icons/next_icon.svg
    - assets/icons/previous_icon.svg
    - assets/icons/back_icon.svg
    - assets/sounds/missedShotSound.mp3
    - assets/sounds/successfulShotSound.mp3
    - assets/icons/pitball_logo_hd.jpeg
    - assets/icons/trophy_1.svg
    - assets/icons/trophy_3.png
    - assets/icons/trophy_4.png
    - assets/icons/trophy_5.png
    - assets/icons/trophy_6.png
    - assets/icons/trophy_7.png
    - assets/icons/trophy_7_fixed.png
    - assets/icons/kings_crown.png
    - assets/icons/KAIHL_LOGO_MAVİ.png
    - assets/icons/KAIHL_LOGO_YAZILI.png

  fonts:
    - family: MyBrandFont
      fonts:
        - asset: assets/fonts/HindSiliguri-SemiBold.ttf
    - family: MyTonicFont
      fonts:
        - asset: assets/fonts/InriaSans-Bold.ttf
    - family: MyBeatifulFont
      fonts:
        - asset: assets/fonts/IndieFlower-Regular.ttf
    - family: MyThinFont
      fonts:
        - asset: assets/fonts/Inter_18pt-Medium.ttf
    - family: MyDigitalFont
      fonts:
        - asset: assets/fonts/digital-7.ttf
